# Generated by Django 6.0.2 on 2026-03-11 11:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0009_verification_fraud_checks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationfraudcheck',
            name='checked_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='verificationreview',
            name='reviewed_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='verificationstatuslog',
            name='changed_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
