# Generated by Django 6.0.2 on 2026-03-11 00:00

import django.db.models.deletion
from django.db import migrations, models
from django.db.models import Q


def seed_product_inventory(apps, schema_editor):
    """Backfill inventory records for existing products."""
    Product = apps.get_model('listings', 'Product')
    ProductInventory = apps.get_model('listings', 'ProductInventory')
    for product in Product.objects.all().only('id', 'quantity_available'):
        ProductInventory.objects.get_or_create(
            product_id=product.id,
            defaults={
                'available_quantity': product.quantity_available,
                'reserved_quantity': 0,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('available_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('reserved_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='listings.product')),
            ],
            options={
                'db_table': 'product_inventory',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='productinventory',
            constraint=models.CheckConstraint(condition=Q(available_quantity__gte=0), name='product_inventory_available_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='productinventory',
            constraint=models.CheckConstraint(condition=Q(reserved_quantity__gte=0), name='product_inventory_reserved_gte_zero'),
        ),
        migrations.RunPython(seed_product_inventory, migrations.RunPython.noop),
    ]
