# Generated by Django 6.0.2 on 2026-03-11 00:00

import django.db.models.deletion
from django.db import migrations, models
from django.db.models import Q
from django.utils import timezone


def backfill_pricing_and_inventory(apps, schema_editor):
    """Create pricing records and sync inventory from legacy fields."""
    Product = apps.get_model('listings', 'Product')
    ProductPricing = apps.get_model('listings', 'ProductPricing')
    ProductInventory = apps.get_model('listings', 'ProductInventory')
    for product in Product.objects.all().only(
        'id',
        'price_per_unit',
        'quantity_available',
        'created_at',
    ):
        ProductPricing.objects.get_or_create(
            product_id=product.id,
            valid_from=product.created_at or timezone.now(),
            defaults={
                'currency': 'USD',
                'price': product.price_per_unit,
                'discount': 0,
                'valid_to': None,
            },
        )
        inventory = ProductInventory.objects.filter(product_id=product.id).first()
        if inventory:
            inventory.available_quantity = product.quantity_available
            inventory.save(update_fields=['available_quantity', 'updated_at'])


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_product_inventory'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('url', models.URLField()),
                ('media_type', models.CharField(max_length=32)),
                ('position', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='listings.product')),
            ],
            options={
                'db_table': 'product_media',
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('valid_from', models.DateTimeField(default=timezone.now)),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing', to='listings.product')),
            ],
            options={
                'db_table': 'product_pricing',
                'ordering': ['-valid_from', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='productmedia',
            constraint=models.UniqueConstraint(fields=('product', 'position'), name='product_media_unique_position'),
        ),
        migrations.AddConstraint(
            model_name='productpricing',
            constraint=models.CheckConstraint(condition=Q(price__gt=0), name='product_pricing_price_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='productpricing',
            constraint=models.CheckConstraint(condition=Q(discount__gte=0), name='product_pricing_discount_gte_zero'),
        ),
        migrations.RunPython(backfill_pricing_and_inventory, migrations.RunPython.noop),
        migrations.RemoveConstraint(
            model_name='product',
            name='products_price_per_unit_gt_zero',
        ),
        migrations.RemoveConstraint(
            model_name='product',
            name='products_quantity_available_gte_zero',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_per_unit',
        ),
        migrations.RemoveField(
            model_name='product',
            name='quantity_available',
        ),
    ]
