# Generated by Django 6.0.2 on 2026-03-11 00:00

import uuid
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_device_tracking'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginVerificationChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('challenge_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('device_identifier', models.CharField(blank=True, max_length=128)),
                ('device_name', models.CharField(blank=True, max_length=120)),
                ('device_type', models.CharField(choices=[('web', 'Web'), ('mobile', 'Mobile'), ('tablet', 'Tablet'), ('desktop', 'Desktop'), ('other', 'Other')], default='other', max_length=32)),
                ('operating_system', models.CharField(blank=True, max_length=120)),
                ('browser', models.CharField(blank=True, max_length=120)),
                ('app_version', models.CharField(blank=True, max_length=64)),
                ('user_agent', models.CharField(blank=True, max_length=512)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('code_hash', models.CharField(max_length=64)),
                ('debug_code', models.CharField(blank=True, max_length=12)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('max_attempts', models.PositiveSmallIntegerField(default=5)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('expired', 'Expired'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('expires_at', models.DateTimeField()),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_challenges', to='users.user')),
            ],
            options={
                'db_table': 'login_verification_challenges',
                'ordering': ['-created_at'],
            },
        ),
    ]
