# Generated by Django 6.0.2 on 2026-03-11 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_role_system'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginRateLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scope', models.CharField(choices=[('ip', 'IP'), ('device', 'Device'), ('user', 'User')], max_length=16)),
                ('key', models.CharField(max_length=191)),
                ('action', models.CharField(default='login', max_length=32)),
                ('window_started_at', models.DateTimeField()),
                ('last_attempt_at', models.DateTimeField()),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('blocked_until', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'login_rate_limits',
                'ordering': ['-last_attempt_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='loginratelimit',
            constraint=models.UniqueConstraint(fields=('scope', 'key', 'action'), name='unique_login_rate_limit_scope_key_action'),
        ),
    ]
