# Generated by Django 6.0.2 on 2026-03-11 13:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_login_rate_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginratelimit',
            name='last_attempt_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='loginratelimit',
            name='window_started_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
